attempting to improve the autogen.sh script
shellcheck warnings for it are all silenced now; still kinda broken, though...

diff --git a/build-aux/csharpcomp.sh.in b/build-aux/csharpcomp.sh.in
--- a/build-aux/csharpcomp.sh.in
+++ b/build-aux/csharpcomp.sh.in
@@ -1,12 +1,12 @@
 #!/bin/sh
 # Compile a C# program.
 
-# Copyright (C) 2003-2012 Free Software Foundation, Inc.
+# Copyright (C) 2003-2023 Free Software Foundation, Inc.
 # Written by Bruno Haible <bruno@clisp.org>, 2003.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 3 of the License, or
+# the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
@@ -15,7 +15,7 @@
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 # This uses the same choices as csharpcomp.c, but instead of relying on the
 # environment settings at run time, it uses the environment variables
@@ -42,7 +42,7 @@ func_tmpdir ()
   # Use the environment variable TMPDIR, falling back to /tmp. This allows
   # users to specify a different temporary directory, for example, if their
   # /tmp is filled up or too small.
-  : ${TMPDIR=/tmp}
+  : "${TMPDIR=/tmp}"
   {
     # Use the mktemp program if available. If not available, hide the error
     # message.
@@ -65,7 +65,6 @@ func_tmpdir ()
 }
 
 sed_quote_subst='s/\([|&;<>()$`"'"'"'*?[#~=% 	\\]\)/\\\1/g'
-options_cscc=
 options_mcs=
 options_csc="-nologo"
 sources=
@@ -74,7 +73,6 @@ while test $# != 0; do
     -o)
       case "$2" in
         *.dll)
-          options_cscc="$options_cscc -shared"
           options_mcs="$options_mcs -target:library"
           options_csc="$options_csc -target:library"
           ;;
@@ -82,29 +80,24 @@ while test $# != 0; do
           options_csc="$options_csc -target:exe"
           ;;
       esac
-      options_cscc="$options_cscc -o "`echo "$2" | sed -e "$sed_quote_subst"`
       options_mcs="$options_mcs -out:"`echo "$2" | sed -e "$sed_quote_subst"`
       options_csc="$options_csc -out:"`echo "$2" | sed -e "$sed_quote_subst"`
       shift
       ;;
     -L)
-      options_cscc="$options_cscc -L "`echo "$2" | sed -e "$sed_quote_subst"`
       options_mcs="$options_mcs -lib:"`echo "$2" | sed -e "$sed_quote_subst"`
       options_csc="$options_csc -lib:"`echo "$2" | sed -e "$sed_quote_subst"`
       shift
       ;;
     -l)
-      options_cscc="$options_cscc -l "`echo "$2" | sed -e "$sed_quote_subst"`
       options_mcs="$options_mcs -reference:"`echo "$2" | sed -e "$sed_quote_subst"`
       options_csc="$options_csc -reference:"`echo "$2" | sed -e "$sed_quote_subst"`".dll"
       shift
       ;;
     -O)
-      options_cscc="$options_cscc -O"
       options_csc="$options_csc -optimize+"
       ;;
     -g)
-      options_cscc="$options_cscc -g"
       options_mcs="$options_mcs -debug"
       options_csc="$options_csc -debug+"
       ;;
@@ -113,7 +106,6 @@ while test $# != 0; do
       exit 1
       ;;
     *.resources)
-      options_cscc="$options_cscc -fresources="`echo "$1" | sed -e "$sed_quote_subst"`
       options_mcs="$options_mcs -resource:"`echo "$1" | sed -e "$sed_quote_subst"`
       options_csc="$options_csc -resource:"`echo "$1" | sed -e "$sed_quote_subst"`
       ;;
@@ -128,31 +120,26 @@ while test $# != 0; do
   shift
 done
 
-if test -n "@HAVE_CSCC@"; then
-  test -z "$CSHARP_VERBOSE" || echo cscc $options_cscc $sources
-  exec cscc $options_cscc $sources
-else
-  if test -n "@HAVE_MCS@"; then
-    # mcs prints it errors and warnings to stdout, not stderr. Furthermore it
-    # adds a useless line "Compilation succeeded..." at the end. Correct both.
-    sed_drop_success_line='${
+if test -n "@HAVE_MCS@"; then
+  # mcs prints it errors and warnings to stdout, not stderr. Furthermore it
+  # adds a useless line "Compilation succeeded..." at the end. Correct both.
+  sed_drop_success_line='${
 /^Compilation succeeded/d
 }'
-    func_tmpdir
-    trap 'rm -rf "$tmp"' 1 2 3 15
-    test -z "$CSHARP_VERBOSE" || echo mcs $options_mcs $sources
-    mcs $options_mcs $sources > "$tmp"/mcs.err
-    result=$?
-    sed -e "$sed_drop_success_line" < "$tmp"/mcs.err >&2
-    rm -rf "$tmp"
-    exit $result
+  func_tmpdir
+  trap 'rm -rf "$tmp"' HUP INT QUIT TERM
+  test -z "$CSHARP_VERBOSE" || echo mcs $options_mcs $sources
+  mcs $options_mcs $sources > "$tmp"/mcs.err
+  result=$?
+  sed -e "$sed_drop_success_line" < "$tmp"/mcs.err >&2
+  rm -rf "$tmp"
+  exit $result
+else
+  if test -n "@HAVE_CSC@"; then
+    test -z "$CSHARP_VERBOSE" || echo csc $options_csc $sources
+    exec csc $options_csc $sources
   else
-    if test -n "@HAVE_CSC@"; then
-      test -z "$CSHARP_VERBOSE" || echo csc $options_csc $sources
-      exec csc $options_csc $sources
-    else
-      echo 'C# compiler not found, try installing pnet, then reconfigure' 1>&2
-      exit 1
-    fi
+    echo 'C# compiler not found, try installing mono, then reconfigure' 1>&2
+    exit 1
   fi
 fi
